### ISSUE TITLE
引入报错

### ISSUE THREAD

**Issue by branchzero** [lizhiyao/sentry-miniapp#22]
hirdScriptError
utils_1.getGlobalObject is not a function
TypeError: utils_1.getGlobalObject is not a function
    at Object../node_modules/sentry-miniapp/dist/integrations/breadcrumbs.js (http://127.0.0.1:36208/appservice/app.js:15271:22)
    at __webpack_require__ (http://127.0.0.1:36208/appservice/runtime.js:226:23)
    at Object../node_modules/sentry-miniapp/dist/integrations/index.js (http://127.0.0.1:36208/appservice/app.js:15862:21)
    at __webpack_require__ (http://127.0.0.1:36208/appservice/runtime.js:226:23)
    at Object../node_modules/sentry-miniapp/dist/sdk.js (http://127.0.0.1:36208/appservice/app.js:16440:15)
    at __webpack_require__ (http://127.0.0.1:36208/appservice/runtime.js:226:23)
    at Object../node_modules/sentry-miniapp/dist/index.js (http://127.0.0.1:36208/appservice/app.js:15237:13)
    at __webpack_require__ (http://127.0.0.1:36208/appservice/runtime.js:226:23)
    at Object../src/utils/request.ts (http://127.0.0.1:36208/appservice/app.js:23563:14)
    at __webpack_require__

**Comment by lizhiyao** [comment]
你的问题解决了吗？

根据你目前反馈的信息，很难去定位具体的问题。issue 我先关掉，如果你使用还是存在问题，可以直接在此 issue 下回复我。
